extern crate proc_macro;

use proc_macro::TokenStream;
use quote::quote;
use syn::{parse_macro_input, Data, DeriveInput, Fields, Lit};

/// Derive macro que genera la implementación del trait `Tool` para una struct.
///
/// # Atributos del struct
///
/// ```ignore
/// #[derive(Tool)]
/// #[tool(name = "get_weather", description = "Obtiene el clima")]
/// pub struct GetWeather { ... }
/// ```
///
/// # Atributos de campos
///
/// ```ignore
/// #[tool(param(description = "Ciudad a consultar", example = "Madrid"))]
/// city: String,
/// ```
///
/// El macro genera automáticamente:
/// - Un tipo `{Name}Input` con `#[derive(Serialize, Deserialize, JsonSchema)]`
/// - Implementación completa del trait `Tool`
/// - JSON Schema estático para el input
#[proc_macro_derive(Tool, attributes(tool))]
pub fn derive_tool(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as DeriveInput);
    match expand_tool_derive(input) {
        Ok(ts) => ts.into(),
        Err(e) => e.to_compile_error().into(),
    }
}

fn expand_tool_derive(input: DeriveInput) -> syn::Result<proc_macro2::TokenStream> {
    let name = &input.ident;

    // Parse struct-level #[tool(name = "...", description = "...")]
    let (tool_name, tool_desc) = parse_tool_attrs(&input)?;

    // Parse field-level attributes and collect field definitions
    let fields = match &input.data {
        Data::Struct(data) => match &data.fields {
            Fields::Named(fields) => &fields.named,
            _ => {
                return Err(syn::Error::new_spanned(
                    name,
                    "Tool structs must have named fields",
                ))
            }
        },
        _ => {
            return Err(syn::Error::new_spanned(
                name,
                "Tool can only be derived on structs",
            ))
        }
    };

    let input_type_name = syn::Ident::new(&format!("{}Input", name), name.span());

    // Build field definitions for the input type
    let mut field_defs = Vec::new();
    let mut field_names = Vec::new();

    for field in fields {
        let field_name = field.ident.as_ref().unwrap();
        let field_type = &field.ty;
        let (description, default_val) = parse_field_attrs(field)?;

        field_names.push(field_name);

        // Build #[derive(Serialize, Deserialize, JsonSchema)] field with attributes
        let mut field_attrs = Vec::new();
        if let Some(desc) = &description {
            field_attrs.push(quote! {
                #[schemars(description = #desc)]
            });
        }

        if let Some(_default) = &default_val {
            field_attrs.push(quote! {
                #[serde(default)]
            });
        }

        field_defs.push(quote! {
            #(#field_attrs)*
            pub #field_name: #field_type
        });
    }

    // Generate the complete implementation
    let schema_static_name = format!("{}_SCHEMA", name.to_string().to_uppercase());
    let schema_static_ident = syn::Ident::new(&schema_static_name, name.span());

    let schema_fn_name = format!("get_schema_{}", name.to_string().to_lowercase());
    let schema_fn_ident = syn::Ident::new(&schema_fn_name, name.span());

    let expanded = quote! {
        /// Input type auto-generated by `#[derive(Tool)]`.
        #[derive(Debug, Clone, ::serde::Serialize, ::serde::Deserialize, ::schemars::JsonSchema)]
        #[schemars(title = #tool_name)]
        pub struct #input_type_name {
            #(#field_defs),*
        }

        /// JSON Schema estático generado en compile-time.
        static #schema_static_ident: ::std::sync::OnceLock<::serde_json::Value> = ::std::sync::OnceLock::new();

        fn #schema_fn_ident() -> &'static ::serde_json::Value {
            #schema_static_ident.get_or_init(|| {
                ::serde_json::to_value(
                    ::schemars::schema_for!(#input_type_name)
                ).expect("Tool schema must be valid JSON")
            })
        }

        impl ::nexora_core::tool::Tool for #name {
            fn name(&self) -> &str {
                #tool_name
            }

            fn description(&self) -> &str {
                #tool_desc
            }

            fn input_schema(&self) -> ::serde_json::Value {
                #schema_fn_ident().clone()
            }

            async fn execute(
                &self,
                args: ::serde_json::Value,
            ) -> Result<::nexora_core::tool::ToolOutput, ::nexora_core::tool::ToolError> {
                let input: #input_type_name = ::serde_json::from_value(args)
                    .map_err(|e| ::nexora_core::tool::ToolError::InvalidArgs(e.to_string()))?;
                self.run_impl(input).await
            }
        }
    };

    Ok(expanded)
}

fn parse_tool_attrs(input: &DeriveInput) -> syn::Result<(String, String)> {
    let mut name = None;
    let mut description = None;

    for attr in &input.attrs {
        if !attr.path().is_ident("tool") {
            continue;
        }
        attr.parse_nested_meta(|meta| {
            if meta.path.is_ident("name") {
                let value = meta.value()?.parse::<Lit>()?;
                if let Lit::Str(s) = value {
                    name = Some(s.value());
                } else {
                    return Err(meta.error("expected string literal"));
                }
            } else if meta.path.is_ident("description") {
                let value = meta.value()?.parse::<Lit>()?;
                if let Lit::Str(s) = value {
                    description = Some(s.value());
                } else {
                    return Err(meta.error("expected string literal"));
                }
            }
            Ok(())
        })?;
    }

    let name =
        name.ok_or_else(|| syn::Error::new_spanned(input, "missing #[tool(name = \"...\")]"))?;
    let description = description
        .ok_or_else(|| syn::Error::new_spanned(input, "missing #[tool(description = \"...\")]"))?;

    Ok((name, description))
}

fn parse_field_attrs(field: &syn::Field) -> syn::Result<(Option<String>, Option<String>)> {
    let mut description = None;
    let mut default_val = None;

    for attr in &field.attrs {
        if !attr.path().is_ident("tool") {
            continue;
        }
        attr.parse_nested_meta(|meta| {
            if meta.path.is_ident("param") {
                meta.parse_nested_meta(|param_meta| {
                    if param_meta.path.is_ident("description") {
                        let value = param_meta.value()?.parse::<Lit>()?;
                        if let Lit::Str(s) = value {
                            description = Some(s.value());
                        }
                    } else if param_meta.path.is_ident("default") {
                        let value = param_meta.value()?.parse::<Lit>()?;
                        if let Lit::Str(s) = value {
                            default_val = Some(s.value());
                        }
                    }
                    Ok(())
                })?;
            }
            Ok(())
        })?;
    }

    Ok((description, default_val))
}
